#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname $0)/.."

[ "$BRANCH" == "master" ] || exit 0

echo "Deploy ${REPO}:${TAG}"
cat kubernetes/deployment.yml \
  | sed "s,latest,${TAG},g" \
  | sudo kubectl replace -f - --record
